config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :statuses
    get 'allStatuses', to: 'statuses#index', as: :feed

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  root to: 'static_pages#about'

  get '/:id', to: 'profiles#show', as: 'showProfile'

  resources :profiles
    get 'myStatuses/:id', to: 'profiles#show', as: 'myProfile'

  resources :heroes
    get 'myHero/:id', to: 'heroes#show', as: 'myHero'
    get 'createHero/:id', to: 'heroes#create', as: 'newHero'

  resources :actions
    post 'createAction/', to: 'actions#createAction'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    #Create an instance variable which becomes available to views and attempt to pass it a valid user based on form params
    @user = User.find_by_profile_name(params[:id])

    if @user

      @statuses = Status.all.where([("user_id = ? OR recipient_id = ?"),@user.id, @user.id]).order(created_at: :desc)
      render action: :show
    else
      #When a status request the error 404 html format rails will send the 404 page with not found status (404)
      render file: 'public/404', status: 404, formats: [:html]
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_hero.html.erb
<!-- Displays the hero stats -->
<%
	unless current_user.nil?
	myHero = current_user.getHero(current_user.id)
%>
		<% unless myHero.nil? %>
			<div class="hero-stats">
			<table id="heroTable">
				<title>Your Hero</title>
				<tr>
					<th rowspan="6">
						<%= image_tag("Hero_Generic.png", alt: "Hero Generic", size: "100x100")%>
					</th>
					<th>Hero Name</th>
					<td><%= myHero.name %></td>
				</tr>
				<tr>
					<th>Level</th>
					<td><%= myHero.level %></td>
				</tr>
				<tr>
					<th>Gear</th>
					<td>
						<%= myHero.weapon %>
						<br>
						<%= myHero.armor %>
					</td>
				</tr>
				<tr>
					<th>Location</th>
					<td><%= myHero.location %></td>
				</tr>
				<tr>
					<th>Gold</th>
					<td><%= myHero.gold %></td>
				</tr>
				<tr>
					<th>Status</th>
					<td><%= myHero.state %></td>
				</tr>
			</table>
		</div>
	<%end%>
<% end %>

app/views/profiles/show.html.erb
<div class = "page-header">
  <h3>All Statuses for <%= @user.profile_name %></h3>
  <%=
  #Helper Rails method
    image_tag @user.gravatar_url
  %>
</div>
<!--TODO: Remove duplicate code from statuses/show -->
<% if @statuses %>
<!-- TODO: Create unique css for this view -->
  <% @statuses.each do |status| %>
    <div class="status-scroller">
      <div class="status-scroller-content" >
        <div class="status" >
          <div class="row">
            <div class = "display-status" style = "padding-right: 10px; padding-left: 40px;">
              <p>
                <strong>From:</strong>
                <% unless status.user.nil? %>
                  <%= status.user.getProfile %>
                <% end %>
                <strong>&nbspTo:</strong>
                <% unless status.recipient_id.nil? %>
                  <%= status.recipient(status.recipient_id).getProfile %>
                <% end %>&nbsp
                <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
              </p>
              <p><%= status.content %></p>
              <span class="admin">
                | <%= link_to "Edit", edit_status_path(status) %>
                <% if current_user.nil? == false && current_user.getProfile == 'Admin' %>
                | <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %>
                <% end %>
              </span>
            </div>
            <div style="text-align: left;">
                <%= image_tag status.user.gravatar_url, alt: "Hero_Icon", size: "50x50" %>
                <% unless status.user.id == status.recipient_id %>
                  <%= image_tag status.recipient(status.recipient_id).gravatar_url, alt: "Hero_Icon", size: "50x50" %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
<% else %>
  <div class="well">
    <hr />
    No statuses to display.
  </div>
<%end%>