config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :statuses
    get 'allStatuses', to: 'statuses#index', as: :feed

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  root to: 'static_pages#about'

  get '/:id', to: 'profiles#show', as: 'showProfile'

  resources :profiles
    get 'myStatuses/:id', to: 'profiles#show', as: 'myProfile'

  resources :heroes
    get 'myHero/:id', to: 'heroes#show', as: 'myHero'
    get 'createHero/:id', to: 'heroes#create', as: 'newHero'

  resources :actions
    post 'createAction/', to: 'actions#createAction'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    #TODO: Should probably use the find_each(batch_size: 100) to optimize multiple records
    #For now limit to 10
    @statuses = Status.all.limit(10).order(created_at: :desc)
    #@statuses = Status.all.order(created_at: :desc)
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    # Could be rewritten as @status = @user.statuses.new(status_params) if necessary
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      # Modified whitelist to allow all listed fields
      params.require(:status).permit(:user_id, :content, :recipient_id)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_editForm.html.erb
<%= 
# Using simple_form structure, object, options bootstrap style
simple_form_for(@status, html: {class: "form-horizontal"}) do |f| 
%>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= 
    # Automated simple_form submit style
    f.button :submit
    %>
  </div>
<% end %>

app/views/statuses/_form.html.erb
<%= 
# Using simple_form structure, object, options bootstrap style
simple_form_for(@status, html: {class: "form-horizontal"}) do |f| 
%>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= 
    # SimpleForm provides collections for creating drop down options
    # label_method is a function modify the html selection label independenty from the option value
    # NOTE: You must pass the user class "getProfile" method as a symbol ":"
    f.input :recipient_id, collection: User.all.order(profile_name: :asc), label_method: :getProfile, :selected  => current_user.id
  %>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= 
    # Automated simple_form submit style
    f.button :submit
    %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'editForm' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<!-- Modified index html from default -->
<div id="heroPartialContent" class = "status-title">
  <% if user_signed_in? %>
    <%= render partial: "profiles/hero" %>
  <% end %>
</div>
<div class="status-col">
  <h3 style="margin-bottom: 0; padding-bottom: 0;">User musings</h3>
  <h5 style="margin-top: 0; padding-top: 0;"> (aka. last 10 Statuses) </h5>
  <%= link_to "Post New Status", new_status_path, class: "btn btn-info" %>
  <br>
  <div class="status-scroller">
    <div class="status-scroller-content">
      <% @statuses.each do |status| %>
        <div class="status">
          <% unless status.user.nil? %>
            <% fromUser = status.user.getProfile %>
            <div class="row">
              <div class="display-gravatar">
                <%=
                #Helper Rails method
                  image_tag status.user.gravatar_url
                %>
              </div>
              <div class = "display-status">
                <!-- ERB Tags with = are echoing the variables -->
                <strong>From:</strong>
                    <%= fromUser %>
                <strong>&nbspTo:</strong>
                 <% unless status.recipient_id.nil? and status.recipient(status.recipient_id).nil? %>
                    <%= status.recipient(status.recipient_id).getProfile %>
                  <% end %>
                <p><%= status.content %></p>
                <div class="meta">
                  <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
                  <span class="admin">
                    <% if current_user.nil? == false && current_user.getProfile == fromUser %>
                      | <%= link_to "Edit", edit_status_path(status) %>
                    <% end %>
                    <% if current_user.nil? == false && current_user.getProfile == 'Admin' %>
                      | <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %>
                    <% end %>
                  </span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if user_signed_in? %>
  <%
    hero = current_user.getHero(current_user.id)
    unless hero.nil?
  %>
    <div id="actionsPartialContent" class="actions-col">
      <%= render partial: "actions/index"%>
    </div>
  <% end %>
<% end %>

app/views/statuses/new.html.erb
<h1>New status from <%= current_user.getProfile %></h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @status.user.getProfile %>
  <strong>&nbspTo:</strong>
  <%= @status.recipient(@status.recipient_id).getProfile %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>