config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :statuses
    get 'allStatuses', to: 'statuses#index', as: :feed

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  root to: 'static_pages#about'

  get '/:id', to: 'profiles#show', as: 'showProfile'

  resources :profiles
    get 'myStatuses/:id', to: 'profiles#show', as: 'myProfile'

  resources :heroes
    get 'myHero/:id', to: 'heroes#show', as: 'myHero'
    get 'createHero/:id', to: 'heroes#create', as: 'newHero'

  resources :actions
    post 'createAction/', to: 'actions#createAction'

end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  before_action :set_hero, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

# GET /hero/1
# GET /hero/1.json
  def show
    #Create an instance variable which becomes available to views
    @hero =Hero.find_by_user_id(params[:id])

    if @hero
      @actions = @hero.actions.all.order(created_at: :desc)
      render action: :show
    else
      @hero = Hero.new
      render action: :new
    end
  end

  # GET /hero/new
  def new
    @hero = Hero.new
  end

  # GET /hero/1/edit
  def edit
    #Create an instance variable which becomes available to views
    @hero =Hero.find_by_id(params[:id])
    if @hero
      render action: :edit
    end
  end

  # POST /
  # POST /hero.json
  def create
    # Could be rewritten as @hero = @user.hero.new(create_hero_params) if necessary
    @hero = Hero.new(create_hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to :action => 'show', :id => @hero.user_id, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, hero: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hero/1
  # PATCH/PUT /hero/1.json
  def update
    respond_to do |format|
      if @hero.update(update_hero_params)
        format.html { redirect_to :action => 'show', :id =>@hero.user_id, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Strong Params
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_hero
    @hero = Hero.find(params[:id])
  end

  def create_hero_params
    params.require(:hero).permit(:user_id, :name, :location, :state, :weapon, :armor, :level, :gold)
  end

  def update_hero_params
    params.require(:hero).permit(:name)
  end

  def update_hero_stats
    params.require(:hero).permit(:location, :state, :weapon, :armor, :level, :gold)
  end

end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/views/heroes/edit.html.erb
<!-- Change Data -->
<div class="row">
	<div class="span8">
		<% if @hero.errors.any? %>
			<div id="error_explanation">
			<h3><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being updated:</h3>
			<ul>
				<% @hero.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
			</div>
		<% end %>
	</div>
</div>
<% unless @hero.nil? %>
	<div class="row">
		<div class="span4">
			<%= simple_form_for(@hero, html: {class: "simple_form well"}) do |f| %>
				<fieldset>
					<legend>Edit "<%= @hero.name %>"</legend>
					<div>
						<%= f.input :name %><hr>
						Level: <%= @hero.level %><br>
						Gear: <%= @hero.weapon %><br>
						Armor: <%= @hero.armor %><br>
						Location: <%= @hero.location %><br>
						Gold: <%= @hero.gold %><br>
						Status: <%= @hero.state %><hr>
					</div>
					<div class="actions">
						<%= f.submit "Update" %>
					</div>
				</fieldset>
			<% end %>
			</div>
			<div class="span8">
				<h2>Question yourself!</h2>
				<%= image_tag("Hero_Generic.png", alt: "Hero Generic", size: "100x100")%>
			</div>
		</div>
	</div>
<% end %>

app/views/heroes/new.html.erb
  <div class="row">
    <div class="span8">
      <% if @hero.errors.any? %>
          <div id="error_explanation">
            <h3><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h3>
            <ul>
            <% @hero.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
      <% end %>
    </div>
  </div>
<div class="row">
  <div class="span4">
  <%= simple_form_for(@hero, html: {class: "simple_form well"}) do |f| %>
    <fieldset>
      <legend>Create a Hero</legend>
      <div>
        <%= f.input :name %>
        <br>
      </div>
      <div class="actions">
        <%=
          #Hidden field
          f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
        %>
        <%= f.button :submit %>
      </div>
    </fieldset>
  <% end %>
  </div>
  <div class="span8">
    <h2>Join!</h2>
    <%= image_tag("Hero_Generic.png", alt: "Hero Generic", size: "100x100")%>
  </div>
</div>

app/views/heroes/show.html.erb
<div class = "page-header">
  <%if  @hero %>
    <h3>About <%= @hero.name %></h3>
  <% else %>
    <h3>Hero for <%= @hero.user.profile_name %> not found</h3>
  <% end %>
</div>
<!--TODO: Remove duplicate code from actions/_index -->
<div class="row">
  <% if @hero %>
    <%= render partial: "profiles/hero", locals: { user: User.first } %>
    <div>
      <br>
      <%= link_to "Edit Hero" , edit_hero_path(@hero.id)%>
      |
      <%= link_to "Delete Hero" , @hero, method: :delete, data: { confirm: 'Are you sure you want to delete this hero?' } %>
    </div>
    <h3>The epic journey of <%= @hero.name %></h3>
    <% if @actions %>
      <div>
          <!-- TODO: Create unique css for this view -->
          <% @actions.each do |action| %>
            <div class="action-scroller">
              <div class="action-scroller-content">
                <div class="action">
                  <div class="row">
                    <div class="display-gravatar"></div>
                      <div class = "display-status">
                        <strong>
                          <%= "At the " + action.location %>
                        </strong>
                        <p>
                          <%= action.result %>
                        </p>
                          <div>
                            <%= time_ago_in_words(action.created_at) + " ago"%>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
        <% else %>
          <div class="well">
            <hr />
            No Actions to display.
          </div>
        <% end %>
      </div>
    <% else %>
      <hr />
      No hero to display.
  <% end %>
</div>