config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :statuses
    get 'allStatuses', to: 'statuses#index', as: :feed

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  root to: 'static_pages#about'

  get '/:id', to: 'profiles#show', as: 'showProfile'

  resources :profiles
    get 'myStatuses/:id', to: 'profiles#show', as: 'myProfile'

  resources :heroes
    get 'myHero/:id', to: 'heroes#show', as: 'myHero'
    get 'createHero/:id', to: 'heroes#create', as: 'newHero'

  resources :actions
    post 'createAction/', to: 'actions#createAction'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>HeroBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class = "navbar navbar-fixed-top navbar-inverse">
		<div class ="navbar-inner">
			<div class="container">
				<!-- # is no link and brand styles the link -->
				<a href ="/" class="brand"><%= image_tag("Hero_Icon.png", alt: "Hero Icon", size: "20x20", style: "padding-bottom:4px")%> HeroBook </a> 
				<ul class="nav">
					<li><%= link_to "All Statuses" , feed_path %> </li> 
					<% if user_signed_in? %>
						<li><%= link_to "My Statuses" , myProfile_path(current_user.getProfile)%> </li>
						<li><%= link_to "My Hero" , myHero_path(current_user.id)%> </li>
					<% end %>
				</ul>
				<ul class ="nav pull-right">
					<% if user_signed_in? %>
						<li>
							<%= 
								# A pre-existing helper method "rake routes"
								link_to current_user.getProfile, edit_user_registration_path
							%>
						</li>
						<li><%=
								# Sends an htp post:request which requires user confirmation
								link_to "Sign Out" , logout_path
							%>
						</li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</header>
	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class(type.to_s) %>">
				<button class="close" data-dismiss="alert">x</button>
				<%= message %>
			</div>
		<% end %>
		<!-- Allows our content from index.html.erb to display -->
		<%= yield %>
	</div>
	<div class="footer-padding">
		<footer class="footer-bar">
			<div>
				<div class = "footer-left">
					HeroBook v1.1.0 is Copyright &copy; 2015 <a href= "http://www.jorgecomics.com">Jorge Diaz</a>
				</div>
				<div class = "footer-right">
					TreeBook Copyright &copy; 2014 <a href="http://teamtreehouse.com/terms"> Treehouse Island Inc.</a>
				</div>
				<div class = "credits">~&nbsp;&nbsp;for Robyn and Felix&nbsp;&nbsp;~</div>
			</div>
			<div class= "license">
				This work is licensed under a <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareALike 4.0</a> International License
			</div>
		</footer>
	</div>
</body>
</html>